name: Keep Alive Login

on:
  schedule:
    - cron: "0 0 1,31 * *"  # 每月 1 号和 31 号凌晨0点
  workflow_dispatch:       # 支持手动触发

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Elchecki deponejon
        uses: actions/checkout@v4

      - name: Agordi Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instali Playwright
        run: |
          python -m pip install --upgrade pip
          python -m pip install playwright
          python -m playwright install chromium

      - name: Ruli Teni-Salutan-Staton
        env:
          UZANTONOMO: ${{ secrets.UZANTONOMO }}
          PASVORTO: ${{ secrets.PASVORTO }}
        run: |
          python login.py
